version: '3'

services:
  bot:
    build: .
    volumes:
      - ${MEDIA_PATH}:${MEDIA_PATH}
      - ${LOGS_PATH}:/app/logs
      - ${SESSIONS_PATH}:/app/sessions
    command: node ./dist/app.js
    env_file:
      - .env
