version: '3'

services:

  bot:
    build: .
    volumes:
      - ${MEDIA_PATH}:${MEDIA_PATH}
      - ${LOGS_PATH}:${LOGS_PATH}
    working_dir: /code/
    command: node ./dist/app.js
    env_file:
      - .env
